version: 2
jobs:
  build:
    working_directory: ~/Javafx-WebView-Debugger
    docker:
      - image: wtanaka/ubuntu-1604-oracle-java-9
    steps:
      - checkout
      - restore_cache:
          key: Javafx-WebView-Debugger-{{ checksum "pom.xml" }}
      - restore_cache:
          key: Javafx-WebView-Debugger-repo
      - run: ./mvnw deploy
      - run: tar -cvzf output.tar.gz -C target/mvn-repo ./
      - save_cache:
          paths:
            - ~/.m2
          key: Javafx-WebView-Debugger-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - target/mvn-repo
          key: Javafx-WebView-Debugger-repo
      - store_artifacts:
          path: output.tar.gz